name: Deploy Portfolio to AWS S3

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Website to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Verify AWS connection
        run: |
          aws sts get-caller-identity

      - name: Deploy website to S3
        run: |
          aws s3 sync . s3://my-portfolio-bucket-06 \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"

      - name: Deployment successful
        run: |
          echo "Portfolio successfully deployed!"
          echo "S3 Bucket: my-portfolio-bucket-06"